OUTPUT_PATH_SIMULATED = "data/raw/simulated_data.json"
OUTPUT_PATH_PROCESSED = "data/processed/processed_data.json"
INSOLATION_MODEL_RESULT = "model_result/insolation_forest_model.pkl"
AUTOENCODER_MODEL_RESULT = "model_result/mlp_autoencoder_model.pkl"
RANDOM_FOREST_MODEL_RESULT = "model_result/random_forest_model.pkl"
SCALER_RESULT = "model_result/scaler.gz"